# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

before_install:
  - sudo apt-get install -y eurostat
  
language: R
r:
  - oldrel
  - release
  - devel
  
sudo: TRUE

os:
  - linux
  - osx
  
cache: packages


Remotes: rOpenGov/iotables
