# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: required
#cache: packages
#dist: trusty

r:
  - oldrel
  - release
  - devel
  
os:
  - linux
  - osx
  
Remotes: rOpenGov/iotables

env:
 global:
 - GITHUB_REPO ropengov/iotables

#before_install:
  #- sudo apt-get -qq update

  #install pacakges 
  #- R -q -e 'install.packages("eurostat"); 
  #-RScript -e 'install.packages("eurostat")'
  